version: "3.7"
services:
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - chat-redis:/var/lib/redis/data
  chat:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./chat:/opt/app
    links:
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
volumes:
  chat-redis: