version: "3.7"
services:
  chat:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./chat:/opt/app
    ports:
      - '3000:3000'
    # env_file:
    #   - .env