version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - chat-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - chat-redis:/var/lib/redis/data
  chat:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./chat:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
volumes:
  chat-postgres:
  chat-redis: